version: 0.2
#env:
  #parameter-store:
    #LOGIN: LOGIN
    #HOST: HOST
    #Organization: Organization
    #Project: Project

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain arunaws --domain-owner 047719654980 --region us-east-1 --query authorizationToken --output text`
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq 
      # Removed Maven manual install
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz  
      - tar xzvf apache-maven-3.9.4-bin.tar.gz
      - ln -s apache-maven-3.9.4 maven

  build:
    commands:
      - mvn clean install -DskipTests
artifacts:
  files:
    - target/**/*.war
  discard-paths: yes