version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # Get the CodeArtifact auth token and export it
      - echo "Getting CodeArtifact token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain arunaws --domain-owner 047719654980 --region us-east-1 --query authorizationToken --output text)

      # Create .m2 directory if it doesn't exist
      - mkdir -p /root/.m2

      # Dynamically generate the Maven settings.xml with the token
      - echo "Creating settings.xml..."
      - |
        cat > /root/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>codeartifact</id>
              <username>aws</username>
              <password>${CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
          <mirrors>
            <mirror>
              <id>codeartifact</id>
              <name>CodeArtifact</name>
              <url>https://arunaws-047719654980.d.codeartifact.us-east-1.amazonaws.com/maven/Vpro-maven-repos/</url>
              <mirrorOf>!central</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

  pre_build:
    commands:
      - echo "Installing tools..."
      - apt-get update
      - apt-get install -y jq

  build:
    commands:
      - echo "Building the application..."
      - mvn clean install -DskipTests -X  # '-X' for debug logging in case of issues

artifacts:
  files:
    - target/**/*.war
  discard-paths: yes
